<?php

namespace AppBundle\Repository;

/**
 * AdministracjaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdministracjaRepository extends \Doctrine\ORM\EntityRepository
{
}
