<?php

namespace AppBundle\Repository;

/**
 * KursRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KursRepository extends \Doctrine\ORM\EntityRepository
{
}
